import { ReportDefinition } from '../interfaces/report-definition.interface';

export const complianceReportDefinitions: Record<string, ReportDefinition> = {
  'faculty-visit-compliance': {
    type: 'faculty-visit-compliance',
    name: 'Faculty Visit Compliance',
    description: 'Track faculty visit compliance for internship monitoring',
    category: 'Compliance',
    icon: 'schedule',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'mentorName', label: 'Mentor Name', type: 'string', default: true, sortable: true },
      { id: 'department', label: 'Department', type: 'string', default: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true },
      { id: 'assignedStudents', label: 'Assigned Students', type: 'number', default: true },
      { id: 'requiredVisits', label: 'Required Visits', type: 'number', default: true },
      { id: 'completedVisits', label: 'Completed Visits', type: 'number', default: true, sortable: true },
      { id: 'pendingVisits', label: 'Pending Visits', type: 'number', default: true, sortable: true },
      { id: 'compliancePercent', label: 'Compliance %', type: 'number', default: true, sortable: true },
      { id: 'lastVisitDate', label: 'Last Visit Date', type: 'date', default: true },
      { id: 'nextScheduledVisit', label: 'Next Scheduled', type: 'date', default: false },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'month', label: 'Month', type: 'select', required: false, options: [
        { label: 'January', value: 1 },
        { label: 'February', value: 2 },
        { label: 'March', value: 3 },
        { label: 'April', value: 4 },
        { label: 'May', value: 5 },
        { label: 'June', value: 6 },
        { label: 'July', value: 7 },
        { label: 'August', value: 8 },
        { label: 'September', value: 9 },
        { label: 'October', value: 10 },
        { label: 'November', value: 11 },
        { label: 'December', value: 12 },
      ]},
      { id: 'year', label: 'Year', type: 'select', dynamic: true, required: false },
      { id: 'complianceLevel', label: 'Compliance Level', type: 'select', required: false, options: [
        { label: 'Compliant (80%+)', value: 'high' },
        { label: 'Partial (50-80%)', value: 'medium' },
        { label: 'Non-Compliant (<50%)', value: 'low' },
      ]},
    ],
    groupBy: ['institutionName', 'department', 'complianceLevel'],
    sortableColumns: ['mentorName', 'completedVisits', 'pendingVisits', 'compliancePercent'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },

  'monthly-report-compliance': {
    type: 'monthly-report-compliance',
    name: 'Monthly Report Compliance',
    description: 'Student monthly report submission compliance',
    category: 'Compliance',
    icon: 'file-done',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'studentName', label: 'Student Name', type: 'string', default: true, sortable: true },
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true },
      { id: 'branchName', label: 'Branch', type: 'string', default: true },
      { id: 'mentorName', label: 'Mentor', type: 'string', default: true },
      { id: 'companyName', label: 'Company', type: 'string', default: true },
      { id: 'totalReportsExpected', label: 'Expected Reports', type: 'number', default: true },
      { id: 'reportsSubmitted', label: 'Submitted', type: 'number', default: true, sortable: true },
      { id: 'reportsApproved', label: 'Approved', type: 'number', default: true },
      { id: 'reportsPending', label: 'Pending', type: 'number', default: true, sortable: true },
      { id: 'compliancePercent', label: 'Compliance %', type: 'number', default: true, sortable: true },
      { id: 'lastSubmissionDate', label: 'Last Submission', type: 'date', default: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'mentorId', label: 'Mentor', type: 'select', dynamic: true, required: false },
      { id: 'month', label: 'Month', type: 'select', required: false, options: [
        { label: 'January', value: 1 },
        { label: 'February', value: 2 },
        { label: 'March', value: 3 },
        { label: 'April', value: 4 },
        { label: 'May', value: 5 },
        { label: 'June', value: 6 },
        { label: 'July', value: 7 },
        { label: 'August', value: 8 },
        { label: 'September', value: 9 },
        { label: 'October', value: 10 },
        { label: 'November', value: 11 },
        { label: 'December', value: 12 },
      ]},
      { id: 'year', label: 'Year', type: 'select', dynamic: true, required: false },
    ],
    groupBy: ['branchName', 'mentorName', 'complianceLevel'],
    sortableColumns: ['studentName', 'reportsSubmitted', 'reportsPending', 'compliancePercent'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },

  'joining-report-status': {
    type: 'joining-report-status',
    name: 'Joining Report Status',
    description: 'Track joining letter/report submission status',
    category: 'Compliance',
    icon: 'file-add',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'studentName', label: 'Student Name', type: 'string', default: true, sortable: true },
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true },
      { id: 'branchName', label: 'Branch', type: 'string', default: true },
      { id: 'companyName', label: 'Company', type: 'string', default: true },
      { id: 'internshipStartDate', label: 'Internship Start', type: 'date', default: true },
      { id: 'joiningLetterStatus', label: 'Joining Letter Status', type: 'string', default: true },
      { id: 'joiningLetterSubmittedAt', label: 'Submitted At', type: 'date', default: true },
      { id: 'joiningLetterApprovedAt', label: 'Approved At', type: 'date', default: false },
      { id: 'daysSinceStart', label: 'Days Since Start', type: 'number', default: true, sortable: true },
      { id: 'mentorName', label: 'Mentor', type: 'string', default: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'joiningLetterStatus', label: 'Status', type: 'select', required: false, options: [
        { label: 'Pending', value: 'PENDING' },
        { label: 'Submitted', value: 'SUBMITTED' },
        { label: 'Approved', value: 'APPROVED' },
        { label: 'Rejected', value: 'REJECTED' },
      ]},
    ],
    groupBy: ['branchName', 'joiningLetterStatus'],
    sortableColumns: ['studentName', 'internshipStartDate', 'daysSinceStart'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },
};
