import { ReportDefinition } from "../interfaces/report-definition.interface";


export const instituteReportDefinitions: Record<string, ReportDefinition> = {
  'institute-summary': {
    type: 'institute-summary',
    name: 'Institution Summary',
    description: 'Comprehensive summary of all institutions',
    category: 'Institute',
    icon: 'bank',
    availableFor: ['STATE_DIRECTORATE', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'name', label: 'Institution Name', type: 'string', default: true, sortable: true },
      { id: 'code', label: 'Code', type: 'string', default: true },
      { id: 'type', label: 'Type', type: 'string', default: true },
      { id: 'city', label: 'City', type: 'string', default: true, sortable: true },
      { id: 'district', label: 'District', type: 'string', default: true },
      { id: 'totalStudents', label: 'Total Students', type: 'number', default: true, sortable: true },
      { id: 'totalFaculty', label: 'Total Faculty', type: 'number', default: true },
      { id: 'totalBranches', label: 'Branches', type: 'number', default: true },
      { id: 'activeInternships', label: 'Active Internships', type: 'number', default: true, sortable: true },
      { id: 'completedInternships', label: 'Completed', type: 'number', default: true },
      { id: 'placementRate', label: 'Placement Rate %', type: 'number', default: true, sortable: true },
      { id: 'isActive', label: 'Active', type: 'boolean', default: false },
    ],
    filters: [
      { id: 'district', label: 'District', type: 'select', dynamic: true, required: false },
      { id: 'city', label: 'City', type: 'select', dynamic: true, required: false },
      { id: 'type', label: 'Institution Type', type: 'select', dynamic: true, required: false },
      { id: 'isActive', label: 'Status', type: 'select', required: false, options: [
        { label: 'Active', value: true },
        { label: 'Inactive', value: false },
      ]},
    ],
    groupBy: ['district', 'city', 'type'],
    sortableColumns: ['name', 'city', 'totalStudents', 'activeInternships', 'placementRate'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },

  'institute-comparison': {
    type: 'institute-comparison',
    name: 'Institution Comparison',
    description: 'Compare performance metrics across institutions',
    category: 'Institute',
    icon: 'bar-chart',
    availableFor: ['STATE_DIRECTORATE', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'name', label: 'Institution Name', type: 'string', default: true, sortable: true },
      { id: 'code', label: 'Code', type: 'string', default: true },
      { id: 'district', label: 'District', type: 'string', default: true },
      { id: 'totalStudents', label: 'Students', type: 'number', default: true, sortable: true },
      { id: 'internshipRate', label: 'Internship Rate %', type: 'number', default: true, sortable: true },
      { id: 'complianceRate', label: 'Compliance Rate %', type: 'number', default: true, sortable: true },
      { id: 'placementRate', label: 'Placement Rate %', type: 'number', default: true, sortable: true },
      { id: 'avgVisitsPerStudent', label: 'Avg Visits/Student', type: 'number', default: true },
      { id: 'avgReportsSubmitted', label: 'Avg Reports', type: 'number', default: true },
      { id: 'overallScore', label: 'Overall Score', type: 'number', default: true, sortable: true },
    ],
    filters: [
      { id: 'district', label: 'District', type: 'multiSelect', dynamic: true, required: false },
      { id: 'academicYear', label: 'Academic Year', type: 'select', dynamic: true, required: false },
    ],
    groupBy: ['district'],
    sortableColumns: ['name', 'totalStudents', 'internshipRate', 'complianceRate', 'placementRate', 'overallScore'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },

  'branch-wise-summary': {
    type: 'branch-wise-summary',
    name: 'Branch-wise Summary',
    description: 'Performance summary by branch across institutions',
    category: 'Institute',
    icon: 'apartment',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'branchName', label: 'Branch', type: 'string', default: true, sortable: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
      { id: 'totalStudents', label: 'Total Students', type: 'number', default: true, sortable: true },
      { id: 'assignedMentors', label: 'Mentors', type: 'number', default: true },
      { id: 'studentsWithInternship', label: 'With Internship', type: 'number', default: true },
      { id: 'internshipRate', label: 'Internship Rate %', type: 'number', default: true, sortable: true },
      { id: 'activeInternships', label: 'Active', type: 'number', default: true },
      { id: 'completedInternships', label: 'Completed', type: 'number', default: true },
      { id: 'avgComplianceScore', label: 'Compliance %', type: 'number', default: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'branchId', label: 'Branch', type: 'multiSelect', dynamic: true, required: false },
    ],
    groupBy: ['institutionName'],
    sortableColumns: ['branchName', 'institutionName', 'totalStudents', 'internshipRate'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },
};
