import { ReportDefinition } from '../interfaces/report-definition.interface';

export const internshipReportDefinitions: Record<string, ReportDefinition> = {
  'internship-applications': {
    type: 'internship-applications',
    name: 'Internship Applications',
    description: 'All internship applications with status tracking',
    category: 'Internship',
    icon: 'file-text',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'studentName', label: 'Student Name', type: 'string', default: true, sortable: true },
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true },
      { id: 'branchName', label: 'Branch', type: 'string', default: true, sortable: true },
      { id: 'companyName', label: 'Company', type: 'string', default: true, sortable: true },
      { id: 'jobProfile', label: 'Job Profile', type: 'string', default: true },
      { id: 'status', label: 'Status', type: 'string', default: true, sortable: true },
      { id: 'appliedDate', label: 'Applied Date', type: 'date', default: true, sortable: true },
      { id: 'startDate', label: 'Start Date', type: 'date', default: true },
      { id: 'endDate', label: 'End Date', type: 'date', default: true },
      { id: 'duration', label: 'Duration (weeks)', type: 'number', default: true },
      { id: 'stipend', label: 'Stipend', type: 'number', default: false },
      { id: 'isSelfIdentified', label: 'Self Identified', type: 'boolean', default: true },
      { id: 'mentorName', label: 'Mentor', type: 'string', default: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'status', label: 'Status', type: 'select', required: false, options: [
        { label: 'Draft', value: 'DRAFT' },
        { label: 'Submitted', value: 'SUBMITTED' },
        { label: 'Under Review', value: 'UNDER_REVIEW' },
        { label: 'Approved', value: 'APPROVED' },
        { label: 'Rejected', value: 'REJECTED' },
        { label: 'Selected', value: 'SELECTED' },
      ]},
      { id: 'dateRange', label: 'Applied Date Range', type: 'dateRange', required: false },
      { id: 'isSelfIdentified', label: 'Self Identified', type: 'boolean', required: false },
    ],
    groupBy: ['status', 'branchName', 'companyName'],
    sortableColumns: ['studentName', 'companyName', 'status', 'appliedDate', 'branchName'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },

  'internship-by-institution': {
    type: 'internship-by-institution',
    name: 'Internships by Institution',
    description: 'Institution-wise internship distribution',
    category: 'Internship',
    icon: 'bank',
    availableFor: ['STATE_DIRECTORATE', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
      { id: 'institutionCode', label: 'Code', type: 'string', default: true },
      { id: 'city', label: 'City', type: 'string', default: true },
      { id: 'totalStudents', label: 'Total Students', type: 'number', default: true, sortable: true },
      { id: 'activeInternships', label: 'Active Internships', type: 'number', default: true, sortable: true },
      { id: 'completedInternships', label: 'Completed', type: 'number', default: true },
      { id: 'pendingApplications', label: 'Pending', type: 'number', default: true },
      { id: 'selfIdentified', label: 'Self Identified', type: 'number', default: true },
      { id: 'internshipRate', label: 'Internship Rate %', type: 'number', default: true, sortable: true },
    ],
    filters: [
      { id: 'district', label: 'District', type: 'select', dynamic: true, required: false },
      { id: 'city', label: 'City', type: 'select', dynamic: true, required: false },
    ],
    groupBy: ['district', 'city'],
    sortableColumns: ['institutionName', 'totalStudents', 'activeInternships', 'internshipRate'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },

  'internship-by-industry': {
    type: 'internship-by-industry',
    name: 'Internships by Industry',
    description: 'Industry-wise internship distribution',
    category: 'Internship',
    icon: 'shop',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'companyName', label: 'Company', type: 'string', default: true, sortable: true },
      { id: 'industryType', label: 'Industry Type', type: 'string', default: true, sortable: true },
      { id: 'city', label: 'City', type: 'string', default: true },
      { id: 'totalInternships', label: 'Total Internships', type: 'number', default: true, sortable: true },
      { id: 'activeInternships', label: 'Active', type: 'number', default: true },
      { id: 'completedInternships', label: 'Completed', type: 'number', default: true },
      { id: 'avgDuration', label: 'Avg Duration (weeks)', type: 'number', default: true },
      { id: 'avgStipend', label: 'Avg Stipend', type: 'number', default: false },
      { id: 'isVerified', label: 'Verified', type: 'boolean', default: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'industryType', label: 'Industry Type', type: 'select', dynamic: true, required: false },
      { id: 'city', label: 'City', type: 'select', dynamic: true, required: false },
      { id: 'isVerified', label: 'Verified Only', type: 'boolean', required: false },
    ],
    groupBy: ['industryType', 'city'],
    sortableColumns: ['companyName', 'industryType', 'totalInternships'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },

  'self-identified-internships': {
    type: 'self-identified-internships',
    name: 'Self-Identified Internships',
    description: 'Internships identified by students themselves',
    category: 'Internship',
    icon: 'user-add',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'studentName', label: 'Student Name', type: 'string', default: true, sortable: true },
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true },
      { id: 'branchName', label: 'Branch', type: 'string', default: true },
      { id: 'companyName', label: 'Company', type: 'string', default: true, sortable: true },
      { id: 'companyCity', label: 'Company City', type: 'string', default: true },
      { id: 'jobProfile', label: 'Job Profile', type: 'string', default: true },
      { id: 'status', label: 'Status', type: 'string', default: true },
      { id: 'startDate', label: 'Start Date', type: 'date', default: true },
      { id: 'endDate', label: 'End Date', type: 'date', default: true },
      { id: 'verificationStatus', label: 'Verification', type: 'string', default: true },
      { id: 'mentorName', label: 'Mentor', type: 'string', default: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'verificationStatus', label: 'Verification Status', type: 'select', required: false, options: [
        { label: 'Pending', value: 'PENDING' },
        { label: 'Verified', value: 'VERIFIED' },
        { label: 'Rejected', value: 'REJECTED' },
      ]},
      { id: 'dateRange', label: 'Date Range', type: 'dateRange', required: false },
    ],
    groupBy: ['branchName', 'verificationStatus', 'status'],
    sortableColumns: ['studentName', 'companyName', 'startDate'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },
};
