import { ReportDefinition } from '../interfaces/report-definition.interface';

export const mentorReportDefinitions: Record<string, ReportDefinition> = {
  'mentor-list': {
    type: 'mentor-list',
    name: 'Mentor List',
    description: 'Complete list of all faculty mentors',
    category: 'Mentor',
    icon: 'user',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'name', label: 'Name', type: 'string', default: true, sortable: true },
      { id: 'email', label: 'Email', type: 'string', default: true },
      { id: 'phoneNumber', label: 'Phone', type: 'string', default: true },
      { id: 'designation', label: 'Designation', type: 'string', default: true },
      { id: 'department', label: 'Department', type: 'string', default: true, sortable: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
      { id: 'assignedStudents', label: 'Assigned Students', type: 'number', default: true, sortable: true },
      { id: 'activeInternships', label: 'Active Internships', type: 'number', default: true },
      { id: 'visitsCompleted', label: 'Visits Completed', type: 'number', default: true },
      { id: 'isActive', label: 'Active', type: 'boolean', default: false },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'department', label: 'Department', type: 'select', dynamic: true, required: false },
      { id: 'hasAssignments', label: 'Has Assignments', type: 'select', required: false, options: [
        { label: 'Yes', value: true },
        { label: 'No', value: false },
      ]},
    ],
    groupBy: ['department', 'institutionName'],
    sortableColumns: ['name', 'department', 'assignedStudents', 'institutionName'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },

  'mentor-student-assignments': {
    type: 'mentor-student-assignments',
    name: 'Mentor Student Assignments',
    description: 'Mentor to student mapping with assignment details',
    category: 'Mentor',
    icon: 'team',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'mentorName', label: 'Mentor Name', type: 'string', default: true, sortable: true },
      { id: 'mentorEmail', label: 'Mentor Email', type: 'string', default: false },
      { id: 'studentName', label: 'Student Name', type: 'string', default: true, sortable: true },
      { id: 'studentRollNumber', label: 'Roll Number', type: 'string', default: true },
      { id: 'branchName', label: 'Branch', type: 'string', default: true },
      { id: 'companyName', label: 'Company', type: 'string', default: true },
      { id: 'internshipStatus', label: 'Internship Status', type: 'string', default: true },
      { id: 'assignedDate', label: 'Assigned Date', type: 'date', default: true },
      { id: 'lastVisitDate', label: 'Last Visit', type: 'date', default: true },
      { id: 'reportsReviewed', label: 'Reports Reviewed', type: 'number', default: false },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'mentorId', label: 'Mentor', type: 'select', dynamic: true, required: false },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'isActive', label: 'Active Only', type: 'boolean', required: false },
    ],
    groupBy: ['mentorName', 'branchName', 'internshipStatus'],
    sortableColumns: ['mentorName', 'studentName', 'assignedDate'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },

  'mentor-utilization': {
    type: 'mentor-utilization',
    name: 'Mentor Utilization Report',
    description: 'Mentor workload and capacity analysis',
    category: 'Mentor',
    icon: 'pie-chart',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'mentorName', label: 'Mentor Name', type: 'string', default: true, sortable: true },
      { id: 'department', label: 'Department', type: 'string', default: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true },
      { id: 'maxCapacity', label: 'Max Capacity', type: 'number', default: true },
      { id: 'currentAssignments', label: 'Current Assignments', type: 'number', default: true, sortable: true },
      { id: 'utilizationPercent', label: 'Utilization %', type: 'number', default: true, sortable: true },
      { id: 'visitsThisMonth', label: 'Visits This Month', type: 'number', default: true },
      { id: 'pendingVisits', label: 'Pending Visits', type: 'number', default: true },
      { id: 'avgResponseTime', label: 'Avg Response (days)', type: 'number', default: false },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'utilizationLevel', label: 'Utilization Level', type: 'select', required: false, options: [
        { label: 'Under-utilized (<50%)', value: 'low' },
        { label: 'Optimal (50-80%)', value: 'medium' },
        { label: 'Over-utilized (>80%)', value: 'high' },
      ]},
    ],
    groupBy: ['department', 'institutionName', 'utilizationLevel'],
    sortableColumns: ['mentorName', 'currentAssignments', 'utilizationPercent'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },

  'unassigned-students': {
    type: 'unassigned-students',
    name: 'Unassigned Students',
    description: 'Students without mentor assignment',
    category: 'Mentor',
    icon: 'user-delete',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true, sortable: true },
      { id: 'name', label: 'Name', type: 'string', default: true, sortable: true },
      { id: 'email', label: 'Email', type: 'string', default: true },
      { id: 'branchName', label: 'Branch', type: 'string', default: true, sortable: true },
      { id: 'currentYear', label: 'Year', type: 'number', default: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true },
      { id: 'hasInternship', label: 'Has Internship', type: 'boolean', default: true },
      { id: 'registeredDate', label: 'Registered Date', type: 'date', default: true },
      { id: 'daysUnassigned', label: 'Days Unassigned', type: 'number', default: true, sortable: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'currentYear', label: 'Year', type: 'select', required: false, options: [
        { label: '1st Year', value: 1 },
        { label: '2nd Year', value: 2 },
        { label: '3rd Year', value: 3 },
        { label: '4th Year', value: 4 },
      ]},
    ],
    groupBy: ['branchName', 'currentYear', 'institutionName'],
    sortableColumns: ['rollNumber', 'name', 'branchName', 'daysUnassigned'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },
};
