import { ReportDefinition } from '../interfaces/report-definition.interface';

export const pendingReportDefinitions: Record<string, ReportDefinition> = {
  'pending-monthly-visits': {
    type: 'pending-monthly-visits',
    name: 'Pending Monthly Visits',
    description: 'Faculty visits pending for current month',
    category: 'Pending',
    icon: 'clock-circle',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'mentorName', label: 'Mentor Name', type: 'string', default: true, sortable: true },
      { id: 'mentorEmail', label: 'Email', type: 'string', default: false },
      { id: 'mentorPhone', label: 'Phone', type: 'string', default: true },
      { id: 'department', label: 'Department', type: 'string', default: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true },
      { id: 'studentName', label: 'Student', type: 'string', default: true },
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true },
      { id: 'companyName', label: 'Company', type: 'string', default: true },
      { id: 'lastVisitDate', label: 'Last Visit', type: 'date', default: true },
      { id: 'daysSinceLastVisit', label: 'Days Since Visit', type: 'number', default: true, sortable: true },
      { id: 'visitsDue', label: 'Visits Due', type: 'number', default: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'mentorId', label: 'Mentor', type: 'select', dynamic: true, required: false },
      { id: 'urgency', label: 'Urgency', type: 'select', required: false, options: [
        { label: 'Critical (>30 days)', value: 'critical' },
        { label: 'High (15-30 days)', value: 'high' },
        { label: 'Normal (<15 days)', value: 'normal' },
      ]},
    ],
    groupBy: ['institutionName', 'mentorName', 'urgency'],
    sortableColumns: ['mentorName', 'daysSinceLastVisit', 'visitsDue'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },

  'pending-monthly-reports': {
    type: 'pending-monthly-reports',
    name: 'Pending Monthly Reports',
    description: 'Student monthly reports pending submission',
    category: 'Pending',
    icon: 'file-exclamation',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'studentName', label: 'Student Name', type: 'string', default: true, sortable: true },
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true },
      { id: 'branchName', label: 'Branch', type: 'string', default: true },
      { id: 'mentorName', label: 'Mentor', type: 'string', default: true },
      { id: 'companyName', label: 'Company', type: 'string', default: true },
      { id: 'pendingMonth', label: 'Pending Month', type: 'string', default: true },
      { id: 'pendingYear', label: 'Year', type: 'number', default: true },
      { id: 'daysPastDue', label: 'Days Past Due', type: 'number', default: true, sortable: true },
      { id: 'lastSubmittedReport', label: 'Last Submitted', type: 'date', default: true },
      { id: 'totalPendingReports', label: 'Total Pending', type: 'number', default: true, sortable: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'mentorId', label: 'Mentor', type: 'select', dynamic: true, required: false },
      { id: 'month', label: 'Month', type: 'select', required: false, options: [
        { label: 'January', value: 1 },
        { label: 'February', value: 2 },
        { label: 'March', value: 3 },
        { label: 'April', value: 4 },
        { label: 'May', value: 5 },
        { label: 'June', value: 6 },
        { label: 'July', value: 7 },
        { label: 'August', value: 8 },
        { label: 'September', value: 9 },
        { label: 'October', value: 10 },
        { label: 'November', value: 11 },
        { label: 'December', value: 12 },
      ]},
      { id: 'year', label: 'Year', type: 'select', dynamic: true, required: false },
    ],
    groupBy: ['branchName', 'mentorName', 'pendingMonth'],
    sortableColumns: ['studentName', 'daysPastDue', 'totalPendingReports'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },

  'pending-joining-letters': {
    type: 'pending-joining-letters',
    name: 'Pending Joining Letters',
    description: 'Students with pending joining letter submission',
    category: 'Pending',
    icon: 'file-unknown',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'studentName', label: 'Student Name', type: 'string', default: true, sortable: true },
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true },
      { id: 'email', label: 'Email', type: 'string', default: true },
      { id: 'phoneNumber', label: 'Phone', type: 'string', default: true },
      { id: 'branchName', label: 'Branch', type: 'string', default: true },
      { id: 'mentorName', label: 'Mentor', type: 'string', default: true },
      { id: 'companyName', label: 'Company', type: 'string', default: true },
      { id: 'internshipStartDate', label: 'Internship Start', type: 'date', default: true },
      { id: 'daysSinceStart', label: 'Days Since Start', type: 'number', default: true, sortable: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'mentorId', label: 'Mentor', type: 'select', dynamic: true, required: false },
      { id: 'urgency', label: 'Urgency', type: 'select', required: false, options: [
        { label: 'Critical (>14 days)', value: 'critical' },
        { label: 'High (7-14 days)', value: 'high' },
        { label: 'Normal (<7 days)', value: 'normal' },
      ]},
    ],
    groupBy: ['branchName', 'mentorName', 'institutionName'],
    sortableColumns: ['studentName', 'daysSinceStart', 'internshipStartDate'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },

  'pending-mentor-assignments': {
    type: 'pending-mentor-assignments',
    name: 'Pending Mentor Assignments',
    description: 'Students awaiting mentor assignment',
    category: 'Pending',
    icon: 'user-switch',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'studentName', label: 'Student Name', type: 'string', default: true, sortable: true },
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true },
      { id: 'email', label: 'Email', type: 'string', default: true },
      { id: 'branchName', label: 'Branch', type: 'string', default: true, sortable: true },
      { id: 'currentYear', label: 'Year', type: 'number', default: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true },
      { id: 'hasInternship', label: 'Has Internship', type: 'boolean', default: true },
      { id: 'registeredDate', label: 'Registered Date', type: 'date', default: true },
      { id: 'daysPending', label: 'Days Pending', type: 'number', default: true, sortable: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'currentYear', label: 'Year', type: 'select', required: false, options: [
        { label: '1st Year', value: 1 },
        { label: '2nd Year', value: 2 },
        { label: '3rd Year', value: 3 },
        { label: '4th Year', value: 4 },
      ]},
      { id: 'hasInternship', label: 'Has Internship', type: 'boolean', required: false },
    ],
    groupBy: ['branchName', 'currentYear', 'institutionName'],
    sortableColumns: ['studentName', 'branchName', 'daysPending'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },
};
