import { ReportDefinition } from '../interfaces/report-definition.interface';

export const studentReportDefinitions: Record<string, ReportDefinition> = {
  'student-directory': {
    type: 'student-directory',
    name: 'Student Directory',
    description: 'Complete list of all students with their details',
    category: 'Student',
    icon: 'team',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true, sortable: true },
      { id: 'name', label: 'Name', type: 'string', default: true, sortable: true },
      { id: 'email', label: 'Email', type: 'string', default: true },
      { id: 'phoneNumber', label: 'Phone', type: 'string', default: false },
      { id: 'branchName', label: 'Branch', type: 'string', default: true, sortable: true },
      { id: 'currentYear', label: 'Year', type: 'number', default: true, sortable: true },
      { id: 'currentSemester', label: 'Semester', type: 'number', default: true },
      { id: 'institutionName', label: 'Institution', type: 'string', default: true, sortable: true },
      { id: 'mentorName', label: 'Mentor', type: 'string', default: true },
      { id: 'internshipStatus', label: 'Internship Status', type: 'string', default: true },
      { id: 'isActive', label: 'Active', type: 'boolean', default: false },
      { id: 'createdAt', label: 'Registered On', type: 'date', default: false },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'currentYear', label: 'Year', type: 'select', required: false, options: [
        { label: '1st Year', value: 1 },
        { label: '2nd Year', value: 2 },
        { label: '3rd Year', value: 3 },
        { label: '4th Year', value: 4 },
      ]},
      { id: 'isActive', label: 'Status', type: 'select', required: false, options: [
        { label: 'Active', value: true },
        { label: 'Inactive', value: false },
      ]},
    ],
    groupBy: ['branchName', 'currentYear', 'institutionName'],
    sortableColumns: ['rollNumber', 'name', 'branchName', 'currentYear', 'institutionName'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },

  'student-internship-status': {
    type: 'student-internship-status',
    name: 'Student Internship Status',
    description: 'Students categorized by their internship status',
    category: 'Student',
    icon: 'solution',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'FACULTY', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true, sortable: true },
      { id: 'name', label: 'Name', type: 'string', default: true, sortable: true },
      { id: 'branchName', label: 'Branch', type: 'string', default: true },
      { id: 'mentorName', label: 'Mentor', type: 'string', default: true },
      { id: 'internshipStatus', label: 'Status', type: 'string', default: true },
      { id: 'companyName', label: 'Company', type: 'string', default: true },
      { id: 'startDate', label: 'Start Date', type: 'date', default: true },
      { id: 'endDate', label: 'End Date', type: 'date', default: true },
      { id: 'reportsSubmitted', label: 'Reports Submitted', type: 'number', default: true },
      { id: 'visitsCompleted', label: 'Visits Completed', type: 'number', default: false },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'internshipStatus', label: 'Internship Status', type: 'select', required: false, options: [
        { label: 'Not Started', value: 'NOT_STARTED' },
        { label: 'In Progress', value: 'IN_PROGRESS' },
        { label: 'Completed', value: 'COMPLETED' },
      ]},
      { id: 'mentorId', label: 'Mentor', type: 'select', dynamic: true, required: false },
    ],
    groupBy: ['internshipStatus', 'branchName', 'mentorName'],
    sortableColumns: ['rollNumber', 'name', 'branchName', 'internshipStatus'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },

  'student-compliance': {
    type: 'student-compliance',
    name: 'Student Compliance Report',
    description: 'Track student compliance with reporting requirements',
    category: 'Student',
    icon: 'audit',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'rollNumber', label: 'Roll Number', type: 'string', default: true, sortable: true },
      { id: 'name', label: 'Name', type: 'string', default: true, sortable: true },
      { id: 'branchName', label: 'Branch', type: 'string', default: true },
      { id: 'mentorName', label: 'Mentor', type: 'string', default: true },
      { id: 'joiningReportStatus', label: 'Joining Report', type: 'string', default: true },
      { id: 'monthlyReportsSubmitted', label: 'Monthly Reports', type: 'number', default: true },
      { id: 'monthlyReportsPending', label: 'Pending Reports', type: 'number', default: true },
      { id: 'lastReportDate', label: 'Last Report Date', type: 'date', default: true },
      { id: 'complianceScore', label: 'Compliance %', type: 'number', default: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'branchId', label: 'Branch', type: 'select', dynamic: true, required: false },
      { id: 'complianceLevel', label: 'Compliance Level', type: 'select', required: false, options: [
        { label: 'Compliant (80%+)', value: 'high' },
        { label: 'Partial (50-80%)', value: 'medium' },
        { label: 'Non-Compliant (<50%)', value: 'low' },
      ]},
    ],
    groupBy: ['branchName', 'mentorName', 'complianceLevel'],
    sortableColumns: ['rollNumber', 'name', 'complianceScore'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },

  'student-by-branch': {
    type: 'student-by-branch',
    name: 'Students by Branch',
    description: 'Student distribution across branches',
    category: 'Student',
    icon: 'apartment',
    availableFor: ['STATE_DIRECTORATE', 'PRINCIPAL', 'SYSTEM_ADMIN'],
    columns: [
      { id: 'branchName', label: 'Branch', type: 'string', default: true, sortable: true },
      { id: 'totalStudents', label: 'Total Students', type: 'number', default: true, sortable: true },
      { id: 'activeInternships', label: 'Active Internships', type: 'number', default: true },
      { id: 'completedInternships', label: 'Completed', type: 'number', default: true },
      { id: 'pendingInternships', label: 'Pending', type: 'number', default: true },
      { id: 'placedStudents', label: 'Placed', type: 'number', default: true },
      { id: 'avgComplianceScore', label: 'Avg Compliance %', type: 'number', default: true },
    ],
    filters: [
      { id: 'institutionId', label: 'Institution', type: 'select', dynamic: true, required: false },
      { id: 'academicYear', label: 'Academic Year', type: 'select', dynamic: true, required: false },
    ],
    groupBy: ['institutionName'],
    sortableColumns: ['branchName', 'totalStudents', 'activeInternships'],
    exportFormats: ['excel', 'csv', 'pdf'],
  },
};
